### ISSUE TITLE
sw2account does not work under zsh

### ISSUE THREAD

**Issue by dirkpetersen** [FredHutch/swift-switch-account#16]
dp@rhino01 ~ % sw2account.py 
Error: too few arguments
usage: sw2account lastname_f
use "sw2account --help" for full help information
dp@rhino01 ~ % 
dp@rhino01 ~ % sw2account.py kxxxxb_c
Error: too few arguments
usage: sw2account lastname_f
use "sw2account --help" for full help information
dp@rhino01 ~ % 
dp@rhino01 ~ % exit

**Comment by atombaby** [comment]
Yes- zsh wasn't working, but this error is a usage error.  When called directly (sw2account.py), a "shell" argument is also required, vis:

    sw2account.py zsh foo_b

However, zsh support is minimal in this iteration- Ubuntu lacks a convenient way (a'la /etc/profile.d for bash) to include zsh rc files in composing the environment.  This is solvable, though it may not be controlled completely through the packaging.

**Comment by atombaby** [comment]
Ok, this is fixed.  Requires a function (in /usr/local/share/zsh/site-functions) and updating RC files (/etc/zsh/zsh{env,rc}

Commit a435cd40a926a0a85a73588bf7c4ef26db80745a
